# Generated by Django 5.2.7 on 2025-10-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='channel',
        ),
        migrations.AddField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default='2c3676ee-b9a1-4722-9fae-8ee57bbb63e8', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.community'),
            preserve_default=False,
        ),
    ]
